### ISSUE TITLE
Limit and log state changes in main control loop

### ISSUE THREAD

**Issue by arlyon** [richardjlyon/pylyric#6]

**Comment by richardjlyon** [comment]
OK - added the limiter, and currently printing temperature to the terminal. Just add the logging on change of state of the heating system

**Comment by arlyon** [comment]
Not sure what the name I should save the data under in influx but there is a comment in the correct spot so just replace it with the influx call.

https://github.com/richardjlyon/pylyric/blob/209792d50a1fe69e67614d898921645eb2b50156/server/app.py#L110

Additionally, the "is_time_to_start_heating" function takes a few parameters which were left blank. I didn't modify it so fill those in and we should be good to go.

**Comment by richardjlyon** [comment]
Son

Did some edits at this end and propose running the controller overnight from my laptop to see how the controller responds.

Is that OK?

There are merge conflicts which we can sort in the morning.

Again, grab your water bottle / open the window - the heating system can go anywhere at this point!

dad x

On 7 Apr 2018, at 23:56, Alexander Lyon <notifications@github.com> wrote:

Not sure what the name I should save the data under in influx but there is a comment in the correct spot so just replace it with the influx call.

https://github.com/richardjlyon/pylyric/blob/209792d50a1fe69e67614d898921645eb2b50156/server/app.py#L110 <https://github.com/richardjlyon/pylyric/blob/209792d50a1fe69e67614d898921645eb2b50156/server/app.py#L110>
Additionally, the "is_time_to_start_heating" function takes a few parameters which were left blank. I didn't modify it so fill those in and we should be good to go.
