### ISSUE TITLE
Experience with changing Lyric thermostat

### ISSUE THREAD

**Issue by mrose17** [richardjlyon/pylyric#8]
i'm one of the maintainers of https://github.com/d0n4v4nb3ck3r/homebridge-honeywell-home and am getting some odd errors from the API. the documentation at https://developer.honeywell.com/lyric/apis/post/devices/thermostats/%7BdeviceId%7D doesn't enumerate the possible errors.

during your development have you ever seen something like this:

    POST thermostat: Error: HTTP response 500 Server Error
    payload: {"mode":"Heat","coolSetpoint":73,"heatSetpoint":70,"thermostatSetpointStatus":"TemporaryHold"}
    details: { code: 500, message: 'Script Execution Failed’ }

any help is appreciated!

thanks,

/mtr
cc: @d0n4v4nb3ck3r

**Comment by donavanbecker** [comment]
@richardjlyon This can be closed.
